import { ArrowUpRight, ArrowDown, Trophy, UsersRound, Shuffle, Check, Medal, Ticket, CircleDot, ChevronDown, Flag } from 'lucide-react';

const contents = [
  { number: '01', name: 'Đôi Nam', pair: 'Nam A + Nam B', text: 'Cùng đồng đội nam tạo nên một cặp đấu ăn ý.' },
  { number: '02', name: 'Đôi Nữ', pair: 'Nữ A + Nữ B', text: 'Phối hợp nhịp nhàng, chinh phục từng điểm số.' },
  { number: '03', name: 'Đôi Nam – Nữ', pair: '1 Nam + 1 Nữ', text: 'Đổi cặp khi gặp đội mới. Mỗi lần ráp kèo, một trải nghiệm.' },
];

export default function Home() {
  return (
    <>
      <a href="#main" className="skip-link">Đến nội dung chính</a>
      <header className="header">
        <a className="brand" href="#" aria-label="532 Sports — đầu trang"><img src="/assets/logo-532.png" width="52" height="52" alt="Logo 532 Sport" /><span>532 <b>SPORTS</b><small>PICKLEBALL CLUB</small></span></a>
        <nav className="desktop-nav" aria-label="Điều hướng chính"><a href="#the-thuc">Thể thức</a><a href="#giai-thuong">Giải thưởng</a><a href="#san-dau">Sân đấu</a></nav>
        <a className="button button-small" href="#tham-gia">Đăng ký qua Zalo <ArrowUpRight size={17} /></a>
      </header>
      <main id="main">
        <section className="hero" aria-labelledby="hero-title">
          <img className="hero-image" src="/assets/san-532-3.jpg" alt="Không gian sân Pickleball 532 Sports có mái che" fetchPriority="high" />
          <div className="hero-shade" />
          <div className="hero-inner container">
            <div className="eyebrow hero-eyebrow"><span className="live-dot" /> MINI GAME THƯỜNG KỲ <span className="season">SEASON 01</span></div>
            <h1 id="hero-title">RÁP KÈO<br /><span>ĐỒNG ĐỘI.</span></h1>
            <p className="hero-copy">Đổi bạn đánh. Kết nối đồng đội.<br />Cùng lên sân, cùng chinh phục tại 532 Sports.</p>
            <div className="hero-actions"><a className="button" href="#the-thuc">Khám phá thể thức <ArrowUpRight size={20} /></a><a className="text-link" href="#giai-thuong">Xem giải thưởng <ArrowDown size={17} /></a></div>
            <div className="hero-bottom"><span><CircleDot size={16} /> PICKLEBALL 532 SPORTS</span><span>CHƠI HẾT MÌNH. KẾT NỐI HẾT CỠ.</span></div>
          </div>
          <div className="hero-stamp" aria-hidden="true"><span>LET’S</span><strong>PLAY.</strong><ArrowUpRight size={36} /></div>
        </section>
        <section className="stats container" aria-label="Thông tin nhanh"><div><strong>04<span>đội</span></strong><p>Tối đa 8 nam & 8 nữ</p></div><div><strong>04<span>người / đội</span></strong><p>2 nam + 2 nữ</p></div><div><strong>03<span>nội dung</span></strong><p>Đôi nam · Đôi nữ · Đôi nam–nữ</p></div><div><strong>11<span>điểm</span></strong><p>Chạm 11 là thắng</p></div></section>
        <section className="section container" id="the-thuc">
          <div className="section-top"><div><p className="eyebrow"><span className="dash" /> THỂ THỨC THI ĐẤU</p><h2>Một đội hình.<br />Ba cách tỏa sáng.</h2></div><p className="section-intro">Ban tổ chức bốc thăm, sắp xếp đội cân bằng trình độ: Nam A, Nam B, Nữ A, Nữ B. Mỗi đội gặp 3 đội còn lại theo thể thức vòng tròn.</p></div>
          <div className="formats">{contents.map((item) => <article className="format" key={item.number}><div className="format-top"><span>{item.number}</span><UsersRound size={26} strokeWidth={1.5} /></div><h3>{item.name}</h3><p className="pair">{item.pair}</p><p>{item.text}</p></article>)}</div>
          <div className="shuffle-panel"><div className="shuffle-icon"><Shuffle size={30} /></div><div><p className="eyebrow">ĐIỂM NHẤN CỦA MINI GAME</p><h3>Đổi cặp. Thêm kết nối.</h3><p>Ở nội dung đôi nam–nữ, cặp đấu <strong>phải thay đổi khi gặp đối thủ mới</strong>, để mỗi thành viên có cơ hội phối hợp với đồng đội khác nhau.</p></div><span className="shuffle-label">LUẬT<br /><b>“RÁP KÈO”</b></span></div>
          <div className="scoring"><div className="score-heading"><Flag size={24} /><h3>Chơi rõ luật.<br />Thắng xứng đáng.</h3></div><div><b>01 / ĐIỂM TRẬN</b><p>Chạm <strong>11 điểm</strong> là thắng.<br />Không cần cách biệt 2 điểm.</p></div><div><b>02 / ĐIỂM ĐỘI</b><p>Mỗi trận thắng = <strong>1 điểm</strong>.<br />3 trận mỗi lần gặp, tối đa 3 điểm.</p></div><div><b>03 / XẾP HẠNG</b><p>Xếp theo <strong>tổng số trận thắng</strong>.<br />Bằng điểm: xét hiệu số điểm thắng – thua.</p></div></div>
        </section>
        <section className="prizes-section" id="giai-thuong"><div className="container"><div className="section-top"><div><p className="eyebrow"><span className="dash" /> GIẢI THƯỞNG SEASON 01</p><h2>Hết mình trên sân.<br />Mang vinh quang về.</h2></div><p className="section-intro">Đội có tổng điểm cao nhất sau vòng tròn giành ngôi vô địch. Nếu bằng điểm, xét hiệu số điểm thắng – thua.</p></div><div className="prize-grid"><article className="champion"><div className="prize-title"><span className="eyebrow">01 / VÔ ĐỊCH</span><Trophy size={44} strokeWidth={1.4} /></div><h3>Chạm tay đến cúp.</h3><p className="cash">200.000<span>đ</span></p><p className="cash-caption">TIỀN MẶT DÀNH CHO ĐỘI VÔ ĐỊCH</p><div className="prize-perks"><span><Trophy size={19} /> Cúp vô địch</span><span><Ticket size={19} /> 04 vé Social miễn phí</span></div></article><article className="runner-up"><div className="prize-title"><span className="eyebrow">02 / Á QUÂN</span><Medal size={44} strokeWidth={1.4} /></div><h3>Dấu ấn xứng đáng.</h3><p className="runner-copy">Ghi dấu tinh thần đồng đội<br />và những trận đấu hết mình.</p><div className="prize-perks"><span><Medal size={19} /> Huy chương</span><span><Ticket size={19} /> 04 vé Social miễn phí</span></div></article></div></div></section>
        <section className="section container venue" id="san-dau"><div className="section-top"><div><p className="eyebrow"><span className="dash" /> SÂN NHÀ CỦA NHỮNG KÈO HAY</p><h2>Hẹn nhau tại<br />532 Sports.</h2></div><p className="section-intro">Không gian sân có mái che, sẵn sàng cho những pha bóng và những lần kết nối mới cùng cộng đồng Pickleball.</p></div><div className="venue-gallery"><figure><img src="/assets/san-532-1.jpg" width="2048" height="1536" loading="lazy" alt="Toàn cảnh các sân Pickleball và hệ thống lưới tại 532 Sports" /><figcaption><span>532 SPORTS</span><span>Không gian sân đấu <ArrowUpRight size={16} /></span></figcaption></figure><figure><img src="/assets/san-532-2.jpg" width="2048" height="1536" loading="lazy" alt="Dãy sân Pickleball có mái che tại câu lạc bộ 532 Sports" /><figcaption><span>PICKLEBALL CLUB</span><span>Kết nối đam mê <ArrowUpRight size={16} /></span></figcaption></figure></div></section>
        <section className="join-section" id="tham-gia"><div className="container join-grid"><div><p className="eyebrow"><span className="dash" /> SẴN SÀNG LÊN SÂN?</p><h2>Ráp kèo đủ đội.<br /><span>Lên sân chiến thôi!</span></h2><p>Mini Game thường kỳ dành cho những người yêu Pickleball tại 532 Sports. Cùng thi đấu, giao lưu và tìm thêm những đồng đội ăn ý.</p><div className="schedule-note"><CircleDot size={19} /><span>Tham gia cộng đồng Zalo bên dưới để liên hệ đăng ký và nhận thông tin lịch thi đấu Season 1.</span></div></div><div className="fee-card"><span className="eyebrow">LỆ PHÍ THAM GIA</span><p className="fee">100.000<span>đ</span></p><p className="per-person">/ người</p><div className="fee-divider" /><p className="included">Một buổi chơi, đầy đủ năng lượng.</p><ul><li><Check size={18} /> Tham gia Mini Game</li><li><Check size={18} /> Nước uống</li><li><Check size={18} /> Chuối</li><li><Check size={18} /> Bánh</li></ul><span className="fee-foot"><UsersRound size={17} /> Quy mô tối đa 16 người chơi</span></div></div><div className="container zalo-panel"><a href="/assets/qr.png" target="_blank" rel="noopener noreferrer" className="qr-image-link" aria-label="Mở ảnh mã QR Zalo kích thước đầy đủ"><img src="/assets/qr.png" width="1260" height="1920" loading="lazy" alt="Mã QR tham gia cộng đồng Zalo GIAO LƯU SOCIAL - 532 SPORT" /></a><div className="zalo-copy"><p className="eyebrow">CỘNG ĐỒNG ZALO 532 SPORTS</p><h3>Quét mã. Nhập hội.<br />Sẵn sàng ráp kèo.</h3><p>Mở Zalo và quét mã để tham gia nhóm <strong>GIAO LƯU SOCIAL - 532 SPORT</strong>. Liên hệ ban tổ chức trong nhóm để đăng ký Mini Game và cập nhật lịch thi đấu.</p><a href="/assets/qr.png" download="532-sports-zalo-qr.png" className="button">Tải mã QR Zalo <ArrowDown size={18} /></a><p className="qr-hint">Đang dùng điện thoại? Lưu ảnh QR, sau đó mở trình quét Zalo và chọn ảnh từ thư viện.</p></div></div></section>
        <section className="faq section container"><div><p className="eyebrow"><span className="dash" /> TRƯỚC KHI VÀO TRẬN</p><h2>Nắm luật.<br />Tự tin lên sân.</h2></div><div className="faq-list"><details><summary>Tôi có cần tự lập đội trước không?<ChevronDown size={20} /></summary><p>Ban tổ chức sắp xếp bốc thăm cân bằng trình độ. Mỗi đội gồm 2 nam và 2 nữ, chia thành Nam A, Nam B, Nữ A, Nữ B.</p></details><details><summary>Luật đổi cặp áp dụng cho nội dung nào?<ChevronDown size={20} /></summary><p>Chỉ áp dụng cho đôi nam–nữ. Cặp nam–nữ phải thay đổi khi gặp đội đối thủ mới, để mỗi thành viên có cơ hội phối hợp với các đồng đội khác nhau.</p></details><details><summary>Tỉ số 10–10 có cần thắng cách 2 điểm?<ChevronDown size={20} /></summary><p>Không. Đội chạm 11 điểm trước sẽ thắng trận, kể cả khi tỉ số chung cuộc là 11–10.</p></details><details><summary>Hai đội bằng điểm thì xếp hạng thế nào?<ChevronDown size={20} /></summary><p>Sau khi hoàn thành vòng tròn, các đội được xếp theo tổng số trận thắng. Nếu bằng điểm, ban tổ chức xét hiệu số điểm thắng – thua.</p></details></div></section>
      </main>
      <footer><div className="container footer-main"><a className="brand" href="#"><img src="/assets/logo-532.png" alt="532 Sport" width="48" height="48" /><span>532 <b>SPORTS</b><small>PICKLEBALL CLUB</small></span></a><p>Chung đam mê. Cùng đồng đội.</p><a href="#" className="back-top">Về đầu trang <ArrowUpRight size={18} /></a></div><div className="container footer-bottom"><span>532 Sports · Mini Game thường kỳ</span><span>RÁP KÈO ĐỒNG ĐỘI — SEASON 01</span></div></footer>
    </>
  );
}
